spring:
  application:
    name: task1

  datasource:
    url: ${DB_HOST}
    username: ${DB_NAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
